name = "gluten-free-store-updater"
main = "src/index.js"
compatibility_date = "2024-08-14"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# GitHub関連の設定は環境変数で管理
GITHUB_REPO_OWNER = "kanakugimakoto"
GITHUB_REPO_NAME = "gluten-free-map-simple"
GITHUB_BRANCH = "main"
GITHUB_FILE_PATH = "data/embeddedStores.json"

# GitHub PATは wrangler secret で管理（設定は後で行う）
# GITHUB_TOKEN = "ghp_xxxxxxxxxxxx"