name = "gluten-free-store-updater"
main = "src/index.js"
compatibility_date = "2024-08-14"
compatibility_flags = ["nodejs_compat"]

[vars]
# GitHub関連の設定は環境変数で管理  
GITHUB_REPO_OWNER = "bettger3000"
GITHUB_REPO_NAME = "naco-gluten-free-map"
GITHUB_BRANCH = "main"
GITHUB_FILE_PATH = "data/embeddedStores.json"

# GitHub PATは wrangler secret で管理（設定は後で行う）
# GITHUB_TOKEN = "ghp_xxxxxxxxxxxx"