name = "avatar-upload-worker"
main = "src/index.js"
compatibility_date = "2024-08-18"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "gluten-free-avatars"

[[kv_namespaces]]
binding = "PROFILE_KV"
id = "8301c0acb1bf44ab9364741e142ff417"
preview_id = "32d65dd59b1f4e5a8fe017e482ad689e"

[[kv_namespaces]]
binding = "STORES_KV"
id = "833fb25560d443bc854a38ea1000eb39"
preview_id = "c43b5cad1c6a4a5ea4e41941529f6c8c"

[vars]
# 公開URL
PUBLIC_URL = "https://pub-42410d5d2a514b56a139d945cf8eb47f.r2.dev"
# 許可されたオリジン
ALLOWED_ORIGINS = "https://bettger3000.github.io,http://localhost:3000,file://"